/**
 * Which device is running each committee.
 *
 * One device at a time holds a committee: it alone reports the session, and
 * every other chair's device shows a watch-only view with a Take over button.
 * The holder refreshes its claim with every report (at least every ten seconds
 * while the dashboard is open), and a claim that has gone quiet for longer than
 * CONTROL_TTL_MS — a closed laptop, a dead battery — lapses, so the next chair
 * to open the dashboard picks the committee up without having to ask.
 *
 * The holder's full session travels with the claim, so taking over (or picking
 * up a lapsed committee) carries on exactly where the last device stopped.
 */

/**
 * Long enough to ride out a browser throttling a background tab's timers to
 * once a minute; short enough that a dead laptop does not hold a committee
 * hostage for long.
 */
export const CONTROL_TTL_MS = 90_000;

export interface ControlRow {
  committee_id: string;
  device_id: string;
  holder_name: string | null;
  heartbeat_at: number;
  /** The last reported session, as JSON, in server time. */
  state: string | null;
  state_device_id: string | null;
}

export interface Holder {
  name: string | null;
  heartbeatAt: number;
  /** True when the claim has lapsed and anyone may pick the committee up. */
  stale: boolean;
}

let ensured = false;

/**
 * Created on first use rather than by a migration, so adding device control
 * needs no setup step: an existing deployment just starts using it.
 */
export async function ensureControlTable(db: D1Database): Promise<void> {
  if (ensured) return;
  await db
    .prepare(
      `CREATE TABLE IF NOT EXISTS committee_control (
         committee_id    TEXT PRIMARY KEY,
         device_id       TEXT NOT NULL,
         holder_name     TEXT,
         heartbeat_at    INTEGER NOT NULL,
         state           TEXT,
         state_device_id TEXT
       )`,
    )
    .run();
  ensured = true;
}

export async function readControl(db: D1Database, committeeId: string): Promise<ControlRow | null> {
  return db
    .prepare('SELECT * FROM committee_control WHERE committee_id = ?1')
    .bind(committeeId)
    .first<ControlRow>();
}

export function holderOf(row: ControlRow | null, now: number): Holder | null {
  if (!row) return null;
  return {
    name: row.holder_name,
    heartbeatAt: row.heartbeat_at,
    stale: now - row.heartbeat_at > CONTROL_TTL_MS,
  };
}

/** A device id is generated by the browser; bound it so it cannot be abused. */
export const validDeviceId = (value: unknown): value is string =>
  typeof value === 'string' && /^[\w-]{8,64}$/.test(value);
